# Generated by Django 5.2.4 on 2025-07-06 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtravel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='enderecocliente',
            options={'verbose_name': 'Endereço do Cliente', 'verbose_name_plural': 'Endereços dos Clientes'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('cliente', 'restaurante')},
        ),
        migrations.RemoveField(
            model_name='categoriaproduto',
            name='nome_categoria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='enderecocliente',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome_funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='status_pagamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data_hora_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='troco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='endereco_restaurante',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='horario_funcionamento',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='nome_do_restaurante',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Avaliação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4, verbose_name='Nota (1-5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Nome da Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='enderecocliente',
            name='cep',
            field=models.CharField(default=78840000, max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enderecocliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=10, verbose_name='Preço Unitário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='transacao_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Transação'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Preparo', 'Em Preparo'), ('Em Entrega', 'Em Entrega'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='', max_length=200, verbose_name='Nome do Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='endereco',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(default='', max_length=200, verbose_name='Nome do Restaurante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='foodtravel_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='foodtravel_app.restaurante', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='foodtravel_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='enderecocliente',
            name='rua',
            field=models.CharField(max_length=200, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Contratação'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='foodtravel_app.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtravel_app.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Cartao Credito', 'Cartão de Crédito'), ('Cartao Debito', 'Cartão de Débito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Outro', 'Outro')], max_length=50, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='foodtravel_app.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='foodtravel_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='foodtravel_app.restaurante', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtravel_app.categoriaproduto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='foodtravel_app.restaurante', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='estrelas',
        ),
    ]
